---
title: "Data Visualisation and Neoplasm Loading"
author: "Helitha Dharmadasa - z5451805"
date: "2024-02-23"
output:
  pdf_document: default
  html_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, tidy=TRUE, dpi=360)
```

```{r, message=FALSE}
library(tidyverse)
```

```{r read}
superlife_df <- read_csv("../Data/Processed Data/CLEANED_2024-srcsc-superlife-inforce-dataset.csv")
head(superlife_df)
summary(superlife_df)
```
## Misc Plots for Initial Analysis
```{r}
plot_df <- superlife_df %>%
  filter(Cause.of.Death.Description != "NA") %>%
  mutate(Cause.of.Death.Description = ifelse(nchar(Cause.of.Death.Description) > 20,
            paste0(str_sub(Cause.of.Death.Description, end = 20), "..."), Cause.of.Death.Description)) %>%
  group_by(Cause.of.Death.Description) %>%
  summarise(count = n())

ggplot(plot_df, aes(x = reorder(Cause.of.Death.Description, desc(count)), y = count)) +
  geom_col(fill = "blue", color = "black") +
  labs(title = "Histogram of Cause of Death",
       x = "Cause of Death",
       y = "Count") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(hjust = 0.5))
```

```{r}
neoplasm_df <- superlife_df %>%
  filter(Cause.of.Death.Description == "Neoplasms") %>%
  group_by(Age.at.Death) %>%
  summarise(count = n())

mean <- weighted.mean(neoplasm_df$Age.at.Death, neoplasm_df$count)
median <- median(rep(neoplasm_df$Age.at.Death, times=neoplasm_df$count))

hist <- ggplot(neoplasm_df, aes(x = Age.at.Death, y = count)) +
  geom_col(fill = "blue", color = "black") +
  labs(title = "Histogram of Cause of Death",
       x = "Cause of Death",
       y = "Count") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(hjust = 0.5))

hist + geom_vline(xintercept = mean, color = "red", linetype = "dashed", size = 1) +
  geom_vline(xintercept = median, color = "green", linetype = "dashed", size = 1) 
```

## Generate and write Neoplasm loading based on cancer death rates
```{r}
neoplasm_df <- neoplasm_df %>%
  filter(Age.at.Death >= 50) %>%
  mutate(Weight = count / sum(count)) %>%
  select (Age.at.Death, Weight)

write_csv(neoplasm_df, "../Data/Processed Data/Neoplasm_Mortality_Loading.csv")
```

```{r}
sum(neoplasm_df$Weight)
```


```{r}
neoplasm_df <- superlife_df %>%
  filter(Cause.of.Death.Description == "Neoplasms") %>%
  group_by(Sex, Age.at.Death) %>%
  summarise(count = n())


means <- neoplasm_df %>%
  group_by(Sex) %>%
  summarise(mean = weighted.mean(Age.at.Death, count))

mean_f <- means %>%
  filter(Sex == "F") %>%
  pull(mean)


mean_m <- means %>%
  filter(Sex == "M") %>%
  pull(mean)

hist <- ggplot(neoplasm_df, aes(x = Age.at.Death, y = count, fill=Sex)) +
  geom_col(color = "black", alpha=0.6) +
  labs(title = "Histogram of Cause of Death",
       x = "Cause of Death",
       y = "Count") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title = element_text(hjust = 0.5))

hist + geom_vline(xintercept = mean_f, color = "orange", linetype = "dashed", size = 1) +
  geom_vline(xintercept = mean_m, color = "turquoise", linetype = "dashed", size = 1) 
```
```{r}
# Smoking rate in inforce data
smokers <- superlife_df %>%
  filter(Smoker.Status == "S") %>%
  nrow()

smokers / nrow(superlife_df)
```







